### ISSUE TITLE
Error opening Wikula after upgrade

### ISSUE THREAD

**Issue by hvorragend** [phaidon/Wikula#73]
Upgrade wikula 1.1 => Wikula 2.0.0
URL: /index.php?module=Wiki&type=admin&func=pages

Error message:

```
Fehler bei Zikula CMS Demo

    The 'Wiki' module returned an error in 'pages'.
    SQLSTATE[42S02]: Base table or view not found: 1146 Table 'd00a0a3a.wikula_pages' doesn't exist

    Exception Trace
    #0 Ausnahmefehler in /www/htdocs/w00ae91a/plugins/Doctrine/lib/vendor/Doctrine/DBAL/Connection.php, Zeile 618
    #1 /www/htdocs/w00ae91a/plugins/Doctrine/lib/vendor/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(46): Doctrine\DBAL\Connection->executeQuery('SELECT w0_.id A...', Array, Array)
    #2 /www/htdocs/w00ae91a/plugins/Doctrine/lib/vendor/Doctrine/ORM/Query.php(249): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute(Object(Doctrine\DBAL\Connection), Array, Array)
    #3 /www/htdocs/w00ae91a/plugins/Doctrine/lib/vendor/Doctrine/ORM/AbstractQuery.php(607): Doctrine\ORM\Query->_doExecute()
    #4 /www/htdocs/w00ae91a/plugins/Doctrine/lib/vendor/Doctrine/ORM/AbstractQuery.php(425): Doctrine\ORM\AbstractQuery->execute(Array, 2)
    #5 /www/htdocs/w00ae91a/modules/Wikula/lib/Wikula/Api/User.php(514): Doctrine\ORM\AbstractQuery->getArrayResult()
    #6 [internal function]: Wikula_Api_User->LoadPages(Array)
    #7 /www/htdocs/w00ae91a/lib/util/ModUtil.php(1089): call_user_func(Array, Array)
    #8 /www/htdocs/w00ae91a/lib/util/ModUtil.php(1194): ModUtil::exec('Wikula', 'user', 'LoadPages', Array, true, NULL)
    #9 /www/htdocs/w00ae91a/modules/Wikula/lib/Wikula/Api/Admin.php(190): ModUtil::apiFunc('Wikula', 'user', 'LoadPages', Array)
    #10 [internal function]: Wikula_Api_Admin->getall(Array)
    #11 /www/htdocs/w00ae91a/lib/util/ModUtil.php(1089): call_user_func(Array, Array)
    #12 /www/htdocs/w00ae91a/lib/util/ModUtil.php(1194): ModUtil::exec('Wikula', 'admin', 'getall', Array, true, NULL)
    #13 /www/htdocs/w00ae91a/modules/Wikula/lib/Wikula/Controller/Admin.php(98): ModUtil::apiFunc('Wikula', 'admin', 'getall', Array)
    #14 [internal function]: Wikula_Controller_Admin->pages(Array)
    #15 /www/htdocs/w00ae91a/lib/util/ModUtil.php(1089): call_user_func(Array, Array)
    #16 /www/htdocs/w00ae91a/lib/util/ModUtil.php(1168): ModUtil::exec('Wikula', 'admin', 'pages', Array, false, NULL)
    #17 /www/htdocs/w00ae91a/index.php(78): ModUtil::func('Wikula', 'admin', 'pages', Array)
    #18 {main}
```

The tables are not renamed. They are still using the old prefix.

**Comment by hvorragend** [comment]
Hopefully fixed in https://github.com/phaidon/Wikula/commit/4058a8b887afa36551059239330a94812f0dfd70
